FROM alpine:3.20.0
LABEL org.opencontainers.image.authors="punkerside"
RUN apk update && apk upgrade && apk add curl
RUN curl https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip -o terraform_1.8.4_linux_amd64.zip && \
  unzip terraform_1.8.4_linux_amd64.zip && rm -rf terraform_1.8.4_linux_amd64.zip && mv terraform /usr/bin/
WORKDIR /app
CMD [ "terraform" ]